import {
  bigint,
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { users } from "./users";

export const employerAccounts = pgTable(
  "employer_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .unique()
      .references(() => users.id, { onDelete: "cascade" }),
    companyName: text("company_name").notNull(),
    // ICE: 15-digit Moroccan tax identifier
    ice: text("ice"),
    sector: text("sector"),
    // Per-employee monthly benefit budget in centimes
    benefitBudgetPerEmployee: bigint("benefit_budget_per_employee", {
      mode: "number",
    }).notNull(),
    // Running total of all subsidy disbursements
    totalBudgetUsed: bigint("total_budget_used", { mode: "number" }).default(0).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("idx_employer_user_id").on(t.userId)]
);

export const enrolledEmployees = pgTable(
  "enrolled_employees",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    employerAccountId: uuid("employer_account_id")
      .notNull()
      .references(() => employerAccounts.id, { onDelete: "cascade" }),
    employeeEmail: text("employee_email").notNull(),
    employeeName: text("employee_name").notNull(),
    // Monthly benefit for this employee in centimes
    monthlyBenefit: bigint("monthly_benefit", { mode: "number" }).notNull(),
    // Linked family user if they registered on Riaya
    userId: uuid("user_id").references(() => users.id),
    active: boolean("active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("idx_enrolled_employer").on(t.employerAccountId),
    index("idx_enrolled_email").on(t.employeeEmail),
    index("idx_enrolled_user").on(t.userId),
  ]
);

/**
 * Monthly employer invoice (Module E / §11.4). One row per employer per calendar
 * month, summing every subsidy disbursed that month. Generated by the
 * `employer.invoice` pg-boss sweep; the unique (employer, year, month) index makes
 * the sweep idempotent. Amounts are integer centimes. `ice` is snapshotted at
 * issue time so a later ICE edit doesn't rewrite history. TVA is 0 in v0.1.
 */
export const employerInvoices = pgTable(
  "employer_invoices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    employerAccountId: uuid("employer_account_id")
      .notNull()
      .references(() => employerAccounts.id, { onDelete: "cascade" }),
    periodYear: integer("period_year").notNull(),
    periodMonth: integer("period_month").notNull(), // 1–12
    subsidyTotal: bigint("subsidy_total", { mode: "number" }).notNull(),
    bookingCount: integer("booking_count").default(0).notNull(),
    tva: bigint("tva", { mode: "number" }).default(0).notNull(),
    total: bigint("total", { mode: "number" }).notNull(),
    ice: text("ice"),
    status: text("status").$type<"issued" | "paid">().default("issued").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("uniq_employer_invoice_period").on(
      t.employerAccountId,
      t.periodYear,
      t.periodMonth
    ),
    index("idx_employer_invoice_employer").on(t.employerAccountId),
  ]
);
